#!/usr/bin/env python3
"""Check renderer receipt integrity, not cryptographic renderer authenticity.

Required receipts in qa/ (or ../qa/), matched uniquely to diagrams/<stem>.*.json:
* archify-validate-<stem>.json + archify-deliver-<stem>.json
* repo-flowmap-validate-<stem>.json + repo-flowmap-build-<stem>.json
Validation accepts explicit JSON success or the flowmap validator's [PASS] stdout.
Supplied JSON input/specification bindings must be complete and current; optional
viewId must agree. Metadata-free JSON and native stdout remain supported.
Build/deliver requires explicit success, input (path), specification.sha256 (current
IR bytes), output (path), and artifact.sha256 (current output bytes). Size-only legacy
receipts must be regenerated by a wrapper around a successful renderer invocation.
Native Archify deliver already supplies the input/specification/artifact fields.

Optional archify-svg-<stem>.json or repo-flowmap-svg-<stem>.json extraction receipts
require source (verified deliver/build HTML path), sourceSha256 (HTML bytes), output,
svgSha256, and explicit success. This
additional sourceSha256 must be emitted at extraction time, not backfilled later.
Only verified source/validate/build/output chains may attribute screen or print
assets. Preembedded data URIs must match those verified bytes and the same View.
Explicit print assets additionally require a supported image extension/MIME and
matching image framing (SVG XML or raster signatures), not merely an output hash.
View association uses the source stem resolved uniquely against canonical model View
IDs when a model is available, otherwise against report View IDs. Optional receipt
viewId must agree. DIA remains responsible for source/model semantic consistency.

RCP-000 invalid report/model input; RCP-001 missing validate; RCP-002 failed validate;
RCP-003 missing build/deliver; RCP-004 failed/malformed build/extraction;
RCP-005 artifact digest/size mismatch; RCP-006 missing artifact or valid SHA-256;
RCP-007 unattributed or wrong-View displayed/print bytes; RCP-008 orphan warning;
RCP-009 missing/mismatched input binding or ambiguous source/View association.

Receipts are editable local evidence. Hashes detect drift, not forged receipts or
prove that a renderer ran. Validation stdout alone does not bind validation to IR.
"""
from __future__ import annotations

import sys as _sys
_sys.dont_write_bytecode = True

import argparse
import base64
import binascii
import hashlib
import json
from pathlib import Path
import re
from typing import TypeGuard
from urllib.parse import unquote_to_bytes
import xml.etree.ElementTree as ET

from c4_validation import ValidationReport, load_json, print_report, sha256_file, write_report
from validate_diagram_inputs import (
    FAMILY_ARCHIFY, FAMILY_FLOWMAP, discover_inputs, qa_dirs, resolve_view, source_stem,
)

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_ROOT = SCRIPT_DIR.parent
ARCHIFY_VALIDATE_PREFIX = "archify-validate-"
ARCHIFY_DELIVER_PREFIX = "archify-deliver-"
ARCHIFY_SVG_PREFIX = "archify-svg-"
FLOWMAP_VALIDATE_PREFIX = "repo-flowmap-validate-"
FLOWMAP_BUILD_PREFIX = "repo-flowmap-build-"
FLOWMAP_SVG_PREFIX = "repo-flowmap-svg-"
ALL_PREFIXES = (ARCHIFY_VALIDATE_PREFIX, ARCHIFY_DELIVER_PREFIX, ARCHIFY_SVG_PREFIX,
                FLOWMAP_VALIDATE_PREFIX, FLOWMAP_BUILD_PREFIX, FLOWMAP_SVG_PREFIX)


def scan_receipts(root: Path) -> dict:
    index: dict[str, list[tuple[str, Path]]] = {prefix: [] for prefix in ALL_PREFIXES}
    for directory in qa_dirs(root):
        for path in sorted(directory.glob("*.json")):
            for prefix in ALL_PREFIXES:
                if path.name.startswith(prefix):
                    index[prefix].append((path.name[len(prefix):-5], path))
                    break
    return index


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return ""


def _unique_object(pairs: list) -> dict:
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate receipt key: {key}")
        result[key] = value
    return result


def _load_receipt(path: Path) -> dict | None:
    try:
        data = json.loads(_read_text(path), object_pairs_hook=_unique_object)
    except (ValueError, RecursionError):
        return None
    return data if isinstance(data, dict) else None


def _build_receipt_failed(data: dict) -> str | None:
    if "ok" in data and data["ok"] is not True:
        return "receipt records non-success ok status"
    if "exitCode" in data and (type(data["exitCode"]) is not int or data["exitCode"] != 0):
        return "receipt records nonzero or malformed exitCode"
    if data.get("ok") is not True and "exitCode" not in data:
        return "receipt requires explicit ok:true or exitCode:0"
    return None


def _validate_receipt_ok(path: Path) -> tuple:
    text = _read_text(path)
    try:
        data = json.loads(text, object_pairs_hook=_unique_object)
    except (ValueError, RecursionError):
        # Native bundled flowmap emits stdout, not JSON. Do not treat a PASS
        # substring in a malformed JSON object as native stdout success.
        ok = text.lstrip().startswith("[PASS]") and "[FAIL]" not in text
        return ok, "stdout receipt requires [PASS] without [FAIL]"
    if not isinstance(data, dict):
        return False, "validate receipt is not a JSON object"
    failure = _build_receipt_failed(data)
    return failure is None, failure or ""


def _resolve_output_candidates(root: Path, output: str) -> list:
    candidate = Path(output)
    if candidate.is_absolute():
        return [root / "diagrams" / candidate.name, candidate]
    return [root / candidate, root.parent / candidate]


def _choose_artifact(root: Path, candidates: list) -> Path | None:
    existing = [p for p in candidates if p.is_file()]
    for path in existing:
        if path.resolve().is_relative_to(root.resolve()):
            return path
    return existing[0] if existing else None


def _valid_digest(value: object) -> TypeGuard[str]:
    return isinstance(value, str) and re.fullmatch(r"[0-9a-fA-F]{64}", value) is not None


def _verify_artifact(report: ValidationReport, root: Path, path: Path, data: dict) -> Path | None:
    fields = data.get("artifact")
    fields = fields if isinstance(fields, dict) else {}
    output = data.get("output")
    digest = fields.get("sha256", data.get("svgSha256"))
    size = fields.get("bytes", data.get("outputBytes", data.get("svgBytes")))
    if not isinstance(output, str) or not output.strip() or not _valid_digest(digest):
        report.error("RCP-006", str(path), "artifact requires output path and a 64-hex SHA-256; size is not integrity evidence")
        return None
    try:
        artifact = _choose_artifact(root, _resolve_output_candidates(root, output))
        if artifact is None:
            report.error("RCP-006", str(path), f"artifact does not exist: {output}")
            return None
        if sha256_file(artifact) != digest.lower():
            report.error("RCP-005", str(path), f"artifact sha256 mismatch: {output}")
            return None
        if size is not None and (type(size) is not int or size < 0 or artifact.stat().st_size != size):
            report.error("RCP-005", str(path), f"artifact size mismatch or malformed size: {output}")
            return None
        return artifact.resolve()
    except (OSError, ValueError, RuntimeError) as exc:
        report.error("RCP-006", str(path), f"artifact unreadable: {exc}")
        return None


def _verify_input(report: ValidationReport, root: Path, path: Path, data: dict,
                  source: Path, extraction: bool = False) -> bool:
    specification = data.get("specification")
    specification = specification if isinstance(specification, dict) else {}
    recorded = data.get("source" if extraction else "input")
    digest = data.get("sourceSha256") if extraction else specification.get("sha256")
    try:
        candidate = (_choose_artifact(root, _resolve_output_candidates(root, recorded))
                     if isinstance(recorded, str) and recorded.strip() else None)
        if (candidate is not None and candidate.resolve() == source.resolve()
                and _valid_digest(digest) and sha256_file(source) == digest.lower()):
            return True
    except (OSError, ValueError, RuntimeError):
        pass
    report.error("RCP-009", str(path), f"missing or mismatched current input path/SHA-256 binding: {source.name}")
    return False


def _find_receipt(stem: str, entries: list):
    resolved = resolve_view(stem, [name for name, _ in entries])
    matches = [p for name, p in entries if name == resolved]
    return matches[0] if len(matches) == 1 else None


def _check_source(report: ValidationReport, root: Path, source: Path, family: str,
                  stem: str, receipts: dict, view_id: str | None) -> list:
    validate_prefix, build_prefix = ((ARCHIFY_VALIDATE_PREFIX, ARCHIFY_DELIVER_PREFIX)
                                    if family == FAMILY_ARCHIFY else
                                    (FLOWMAP_VALIDATE_PREFIX, FLOWMAP_BUILD_PREFIX))
    before = len(report.errors)
    validate = _find_receipt(stem, receipts[validate_prefix])
    if validate is None:
        report.error("RCP-001", str(source), "required validate receipt missing or ambiguous")
    else:
        ok, detail = _validate_receipt_ok(validate)
        if not ok:
            report.error("RCP-002", str(validate), detail)
        else:
            data = _load_receipt(validate)
            if data is not None:
                # Optional for native/legacy validation; once supplied, the pair
                # must bind this exact source, not just another successful build.
                if "input" in data or "specification" in data:
                    _verify_input(report, root, validate, data, source)
                if "viewId" in data and data["viewId"] != view_id:
                    report.error("RCP-009", str(validate), "receipt viewId disagrees with source/View association")
    build = _find_receipt(stem, receipts[build_prefix])
    artifact = None
    if build is None:
        report.error("RCP-003", str(source), "required build/deliver receipt missing or ambiguous")
    else:
        data = _load_receipt(build)
        failure = _build_receipt_failed(data) if data is not None else "receipt is not a JSON object"
        if failure:
            report.error("RCP-004", str(build), failure)
        elif data is not None:
            _verify_input(report, root, build, data, source)
            if "viewId" in data and data["viewId"] != view_id:
                report.error("RCP-009", str(build), "receipt viewId disagrees with source/View association")
            artifact = _verify_artifact(report, root, build, data)
    valid_chain = len(report.errors) == before and artifact is not None
    outputs = [artifact] if valid_chain else []
    svg_prefix = ARCHIFY_SVG_PREFIX if family == FAMILY_ARCHIFY else FLOWMAP_SVG_PREFIX
    svg = _find_receipt(stem, receipts[svg_prefix])
    if svg is not None:
        data = _load_receipt(svg)
        failure = _build_receipt_failed(data) if data is not None else "receipt is not a JSON object"
        if failure:
            report.error("RCP-004", str(svg), failure)
        elif data is not None:
            svg_output = _verify_artifact(report, root, svg, data)
            if artifact is None:
                report.error("RCP-009", str(svg), "extraction requires a verified deliver/build artifact")
            elif _verify_input(report, root, svg, data, artifact, extraction=True) and valid_chain and svg_output:
                outputs.append(svg_output)
    return outputs


def _decode_data_uri(uri: object) -> tuple[str, bytes] | None:
    if not isinstance(uri, str) or not uri.startswith("data:"):
        return None
    try:
        header, body = uri.split(",", 1)
        raw = unquote_to_bytes(body)
        if header.lower().endswith(";base64"):
            raw = base64.b64decode(raw, validate=True)
        return header[5:].split(";", 1)[0].lower(), raw
    except (ValueError, binascii.Error, UnicodeError):
        return None


_PRINT_MIMES = {
    ".svg": "image/svg+xml", ".png": "image/png",
    ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".gif": "image/gif",
    ".webp": "image/webp", ".bmp": "image/bmp",
}


def _print_image_matches(mime: str | None, raw: bytes) -> bool:
    """Basic image framing, not full raster decoding or SVG security sanitization."""
    if mime == "image/svg+xml":
        try:
            return ET.fromstring(raw).tag in ("svg", "{http://www.w3.org/2000/svg}svg")
        except (ET.ParseError, ValueError, LookupError):
            return False
    if mime == "image/png":
        return (len(raw) >= 57 and raw.startswith(b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR")
                and int.from_bytes(raw[16:20], "big") > 0
                and int.from_bytes(raw[20:24], "big") > 0 and b"IDAT" in raw[33:-12]
                and raw.endswith(b"\x00\x00\x00\x00IEND\xaeB`\x82"))
    if mime == "image/jpeg":
        return (len(raw) > 4 and raw.startswith(b"\xff\xd8\xff")
                and b"\xff\xda" in raw and raw.endswith(b"\xff\xd9"))
    if mime == "image/gif":
        return (len(raw) > 13 and raw[:6] in (b"GIF87a", b"GIF89a")
                and int.from_bytes(raw[6:8], "little") > 0
                and int.from_bytes(raw[8:10], "little") > 0 and raw.endswith(b";"))
    if mime == "image/webp":
        return (len(raw) >= 20 and raw[:4] == b"RIFF" and raw[8:12] == b"WEBP"
                and int.from_bytes(raw[4:8], "little") == len(raw) - 8
                and raw[12:16] in (b"VP8 ", b"VP8L", b"VP8X"))
    if mime == "image/bmp":
        return (len(raw) >= 26 and raw[:2] == b"BM"
                and int.from_bytes(raw[2:6], "little") == len(raw)
                and 26 <= int.from_bytes(raw[10:14], "little") < len(raw))
    return False


def _check_report_assets(report: ValidationReport, root: Path, data: dict, known: dict) -> None:
    diagrams = data.get("diagrams", [])
    if not isinstance(diagrams, list):
        report.error("RCP-000", "$.diagrams", "diagrams must be an array")
        return
    for index, diagram in enumerate(diagrams):
        location = f"$.diagrams[{index}]"
        if not isinstance(diagram, dict):
            report.error("RCP-000", location, "diagram must be an object")
            continue
        view_id = diagram.get("viewId")
        outputs = known.get(view_id, {}) if isinstance(view_id, str) else {}
        for path_key, uri_key in (("assetPath", "dataUri"), ("printAssetPath", "printDataUri")):
            asset, uri = diagram.get(path_key), diagram.get(uri_key)
            # Absent assets are the documented text/print fallback. Other validators
            # enforce required diagrams; RCP attributes only supplied visual bytes.
            if asset is None and uri is None:
                continue
            target = None
            if isinstance(asset, str) and asset.strip():
                try:
                    target = (root / asset).resolve()
                except (OSError, ValueError, RuntimeError):
                    pass
            if asset is not None and (target is None or target not in outputs):
                report.error("RCP-007", location + "." + path_key, "asset is not a verified renderer output for this View")
            if path_key == "printAssetPath" and target is not None and target in outputs:
                try:
                    printable = _print_image_matches(_PRINT_MIMES.get(target.suffix.lower()), target.read_bytes())
                except OSError:
                    printable = False
                if not printable:
                    report.error("RCP-007", location + "." + path_key, "print asset must be a supported static image with matching file format")
            if uri is not None:
                decoded = _decode_data_uri(uri)
                digest = hashlib.sha256(decoded[1]).hexdigest() if decoded is not None else None
                allowed = [outputs[target]] if target in outputs else list(outputs.values())
                if digest is None or digest not in allowed:
                    report.error("RCP-007", location + "." + uri_key, "embedded bytes do not match a verified renderer output for this View")
                if uri_key == "printDataUri" and (decoded is None or not _print_image_matches(*decoded)):
                    report.error("RCP-007", location + "." + uri_key, "print data URI must have a supported image MIME and matching image bytes")


def run(root: Path, data_path: Path | None = None, skill_root: Path | None = None,
        model_path: Path | None = None) -> ValidationReport:
    """Backward-compatible call signature; model_path optionally anchors View IDs."""
    report = ValidationReport("render-receipts")
    root = Path(root).resolve()
    data = None
    if data_path is not None:
        try:
            data = load_json(Path(data_path))
        except (OSError, ValueError, RuntimeError, RecursionError) as exc:
            report.error("RCP-000", str(data_path), f"report-data unreadable: {exc}")
        if data is not None and not isinstance(data, dict):
            report.error("RCP-000", str(data_path), "report-data must be an object")
            data = None
    view_ids = []
    if data is not None and isinstance(data.get("diagrams"), list):
        view_ids = sorted({d["viewId"] for d in data["diagrams"]
                           if isinstance(d, dict) and isinstance(d.get("viewId"), str)})
    model = Path(model_path) if model_path is not None else root / "model/architecture-model.json"
    if not model.is_absolute():
        model = root / model
    if model.is_file() or model_path is not None:
        try:
            model_data = load_json(model)
            views = model_data.get("views") if isinstance(model_data, dict) else None
            if not isinstance(views, list):
                raise ValueError("model views must be an array")
            view_ids = [v["id"] for v in views if isinstance(v, dict) and isinstance(v.get("id"), str)]
        except (OSError, ValueError, RuntimeError, RecursionError) as exc:
            report.error("RCP-000", str(model), f"model unreadable: {exc}")
    receipts = scan_receipts(root)
    sources = discover_inputs(root)
    source_stems = {family: [source_stem(p) for p, f in sources if f == family]
                    for family in (FAMILY_ARCHIFY, FAMILY_FLOWMAP)}
    known: dict[str, dict[Path, str]] = {}
    for source, family in sources:
        stem = source_stem(source)
        view_id = resolve_view(stem, view_ids)
        if view_ids and view_id is None:
            report.error("RCP-009", str(source), "source cannot resolve to one View")
        outputs = _check_source(report, root, source, family, stem, receipts, view_id)
        if view_id is not None:
            for output in outputs:
                try:
                    known.setdefault(view_id, {})[output] = sha256_file(output)
                except OSError as exc:
                    report.error("RCP-006", str(output), f"artifact unreadable: {exc}")
    for prefix, entries in receipts.items():
        family = FAMILY_ARCHIFY if prefix.startswith("archify-") else FAMILY_FLOWMAP
        for stem, path in entries:
            if resolve_view(stem, source_stems[family]) is None:
                report.warning("RCP-008", str(path), "orphan receipt: never usable for asset attribution")
    if data is not None:
        _check_report_assets(report, root, data, known)
    if not report.errors:
        report.pass_check("RCP-001", "source receipts and supplied report assets verified",
                          f"{len(sources)} source(s); integrity only, not renderer authenticity")
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify renderer receipt integrity and View/asset bindings")
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--data", type=Path, default=None,
                        help="report-data path relative to --root; explicit missing files fail")
    parser.add_argument("--model", type=Path, default=None)
    parser.add_argument("--skill-root", type=Path, default=SKILL_ROOT)
    parser.add_argument("--output-json", type=Path)
    args = parser.parse_args()
    root = args.root.resolve()
    data_path = root / args.data if args.data is not None else root / "html/report-data.json"
    if args.data is None and not data_path.is_file():
        data_path = None
    report = run(root, data_path=data_path, skill_root=args.skill_root.resolve(), model_path=args.model)
    print_report(report)
    if args.output_json:
        write_report(args.output_json, report)
    return 1 if report.errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
